all:
	./jemdoc  -o ../ index.jemdoc
	./jemdoc  -o ../ officer.jemdoc
	./jemdoc  -o ../ member.jemdoc
	./jemdoc  -o ../ subcom.jemdoc
	./jemdoc  -o ../ activity.jemdoc
	./jemdoc  -o ../ letter.jemdoc
	./jemdoc  -o ../ journal.jemdoc
	./jemdoc  -o ../ award.jemdoc
	#./jemdoc  -o ../ shiyanhu.jemdoc
	# special sessions
	./jemdoc  -o ../ TBD-CPS.jemdoc
	./jemdoc  -o ../ TSUSC-CPS.jemdoc
	./jemdoc  -o ../ BOOK-CPSBD.jemdoc
	chmod a+r ../img/committee/*.jpg

